FROM swedishembedded/boot:latest

ARG NODE_VERSION=22

# Non-interactive mode for apt
ENV DEBIAN_FRONTEND=noninteractive

USER root

# Install additional development packages
RUN apt-get -y update && \
    apt-get -y upgrade && \
    apt-get install --no-install-recommends -y \
		bash-completion \
		bc \
		biber \
		btop \
		clangd \
		emacs \
		gdb-multiarch \
		gettext \
		gitk \
		gnutls-dev \
		iputils-ping \
		libacl1-dev \
		libasound2-dev \
		libgbm-dev \
		libgccjit-14-dev \
		libgccjit0 \
		libgtk-3-0 \
		libgtk2.0-0 \
		libjansson-dev \
		libjansson4 \
		libnotify-dev \
		libnss3 \
		libpython3-dev \
		libxss1 \
		libxtst6 \
		luarocks \
		ncurses-dev \
		neovim \
		openbox \
		picocom \
		pre-commit \
		python3-xdg \
		ripgrep \
		tig \
		tmux \
		tree \
		xauth \
		xclip \
		xterm \
		xvfb \
		xz-utils \
		yamllint \
        autoconf \
        automake \
        bison \
        ccache \
        chrpath \
        clang-format \
        cpio \
        cscope \
        device-tree-compiler \
        dfu-util \
        diffstat \
        dos2unix \
        doxygen \
        file \
        flex \
        gawk \
        gcovr \
        git-core \
        gperf \
        help2man \
		host \
        iproute2 \
        lcov \
        libboost-date-time-dev \
        libboost-dev \
        libboost-filesystem-dev \
        libboost-iostreams-dev \
        libboost-python-dev \
        libboost-regex-dev \
        libboost-system-dev \
        libboost-test-dev \
        libcairo2-dev \
        libclang-19-dev \
        libedit-dev \
        libglib2.0-dev \
        libgmp3-dev \
        libgtest-dev \
        libgtk2.0-0 \
        liblocale-gettext-perl \
        libmpfr-dev \
        libncurses5-dev \
        libpcap-dev \
        libpopt0 \
        libsdl1.2-dev \
        libsdl2-dev \
        libssl-dev \
        libtool \
        libtool-bin \
        net-tools \
        octave \
        openssh-client \
        ovmf \
        parallel \
        pkg-config \
        python3-ply \
        qemu-system \
        rsync \
        socat \
        srecord \
        texinfo \
        thrift-compiler \
        tzdata \
        unzip \
        valgrind \
        xz-utils \
        && \
    apt-get clean -y && \
    rm -rf /var/lib/apt/lists/*

# Install multi-lib gcc (x86 only)
RUN if [ "${HOSTTYPE}" = "x86_64" ]; then \
		apt-get -y update && \
		apt-get -y upgrade && \
		apt-get install --no-install-recommends -y \
			gcc-multilib \
			g++-multilib && \
		dpkg --add-architecture i386 && \
		apt-get -y update && \
		apt-get install --no-install-recommends -y \
			libsdl2-dev:i386 && \
		apt-get clean -y && \
		rm -rf /var/lib/apt/lists/* \
	; fi

RUN apt-get update && \
	echo "Installing latest nodejs packages" && \
	curl -sL https://deb.nodesource.com/setup_${NODE_VERSION}.x  | bash - && \
	apt-get -qy install \
		nodejs \
		&& \
	echo "Cleaning up cache.." && \
	apt-get clean -y && \
	apt-get autoremove --purge -y && \
	rm -rf /var/lib/apt/lists/*

# Add Docker's official GPG key
RUN mkdir -p /etc/apt/keyrings && \
    curl -fsSL https://download.docker.com/linux/ubuntu/gpg | tee /etc/apt/keyrings/docker.asc > /dev/null && \
    chmod a+r /etc/apt/keyrings/docker.asc

# Add Docker repository
RUN echo "deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null

# Update apt cache after adding Docker repository
RUN apt-get update

# Install Docker packages
RUN apt-get install -qy \
    docker-ce \
    docker-ce-cli \
    containerd.io \
    docker-buildx-plugin \
    docker-compose-plugin && \
	apt-get clean -y && \
	apt-get autoremove --purge -y && \
	rm -rf /var/lib/apt/lists/*

RUN usermod -aG docker user

# Install GDB dependencies
RUN apt-get update && \
    apt-get install -qy \
        python3-pygments && \
    apt-get clean -y && \
    apt-get autoremove --purge -y && \
    rm -rf /var/lib/apt/lists/*
COPY --chown=user:user conf/pygdbinit /home/user/.pygdbinit

# Create the workspace directory
RUN mkdir /workspaces/ && \
	chown user:user /workspaces/

USER user

# Install python tools
RUN pip3 install --upgrade pip && \
	pip3 install \
		black \
        pre-commit \
		west && \
    sudo chown -R user:user $VIRTUAL_ENV

COPY --chown=user:user conf/.bashrc /home/user/.bashrc

ADD entrypoint.sh /home/user/init

WORKDIR /workspaces/

# Configure default shell and editor
ENV DISPLAY=:0
ENV SHELL=/bin/bash
ENV EDITOR=nvim

# Set the init script
ENTRYPOINT ["/home/user/init"]

# Launch bash shell by default
CMD ["/bin/bash"]
