#!/bin/sh

ROOT="$(readlink -f "$(dirname "$(readlink -f "$0")")/..")"
IMAGES="$1"

. "${ROOT}/scripts/common.sh"

set -x

echo "Building images: $IMAGES for $TAG"

if [ -z "$IMAGES" ]; then
	IMAGES="base ci build devel workstateion"
fi

# Build the build image
for IMAGE in $IMAGES; do
	docker build \
		-f Dockerfile.${IMAGE} \
		-t swedishembedded/${IMAGE}:latest \
		-t swedishembedded/${IMAGE}:$TAG .
done
