#!/bin/sh

ROOT="$(readlink -f "$(dirname "$(readlink -f "$0")")/..")"
IMAGES=$@

. "${ROOT}/scripts/common.sh"

set -e
set -x

echo "Building image(s): $IMAGES for $TAG"

if [ -z "$IMAGES" ]; then
	IMAGES="base build workstation"
fi

# Build the build image
for IMAGE in $IMAGES; do
	docker build \
		-f Dockerfile."${IMAGE}" \
		-t swedishembedded/"${IMAGE}":latest \
		-t swedishembedded/"${IMAGE}":"$TAG" . || {
		echo "BUILD FAILED!!!"
		exit 1
	}
done
