#!/bin/sh

ROOT="$(readlink -f "$(dirname "$(readlink -f "$0")")/..")"

. ${ROOT}/scripts/common.sh

for IMAGE in base ci build devel workstation; do
	sudo docker push swedishembedded/${IMAGE}:$TAG
	sudo docker push swedishembedded/${IMAGE}:latest
done

