#!/bin/bash

sudo apt-get update && \
sudo apt-get install -qy \
	chromium-browser \
	ssh \
	curl \
	obs-studio \
	gitk \
	btop \
	gnome-tweaks \
	flameshot \
	gnome-keyring \
	python3-build \
	python3-venv \
	libfuse2t64

# Set locale settings for English language with Swedish time format
# Set locale in /etc/default/locale directly
sudo bash -c 'cat > /etc/default/locale << EOF
LANG=en_US.UTF-8
LC_TIME=en_GB.UTF-8
LC_NUMERIC=en_GB.UTF-8
LC_MEASUREMENT=en_GB.UTF-8
EOF'

# Get user info from system settings if not already set
EMAIL=$(git config --global user.email)
NAME=$(git config --global user.name)

if [ -z "$EMAIL" ]; then
	echo -n "Enter your email for git: "
	read EMAIL
	if [ -n "$EMAIL" ]; then
		echo "Setting git email to $EMAIL"
		git config --global user.email "$EMAIL"
	fi
fi

if [ -z "$NAME" ]; then
	echo -n "Enter your name for git: "
	read NAME
	if [ -n "$NAME" ]; then
		echo "Setting git name to $NAME"
		git config --global user.name "$NAME"
	fi
fi

git config pull.merge true
