#!/bin/bash

ROOT="$(realpath $(dirname $BASH_SOURCE)/../..)"

sudo apt-get update && sudo apt-get install -qy \
	python3-pygments \
	gdb-multiarch

# gdb setup
cp -R $ROOT/conf/pygdbinit ~/.pygdbinit
