#!/bin/bash

ROOT="$(realpath $(dirname $BASH_SOURCE)/../..)"

sudo apt-get update && sudo apt-get install -qy \
	gdb-multiarch

pip3 install pygments

# gdb setup
cp -R $ROOT/conf/pygdbinit ~/.pygdbinit
