#!/bin/bash

set -e
set -o pipefail

ROOT="$(realpath $(dirname $BASH_SOURCE)/../..)"

sudo apt-get update && sudo apt-get install -qy \
	xfonts-terminus \
	tmux

# Enable terminus bitmap fonts
[[ -e /etc/fonts/conf.d/70-yes-bitmaps.conf ]] && {
	sudo rm /etc/fonts/conf.d/70-yes-bitmaps.conf
}
[[ -e /etc/fonts/conf.d/conf.avail/70-no-bitmaps.conf ]] && {
	sudo ln -s /etc/fonts/conf.d/conf.avail/70-no-bitmaps.conf /etc/fonts/conf.d/
}

cp -R $ROOT/conf/.tmux.* ~/
